#!/usr/bin/env python3
#
# Copyright (c) 2020 Gareth Palmer <gareth.palmer3@gmail.com>
# This program is free software, distributed under the terms of
# the GNU General Public License Version 2.

import sys
import os.path
import re
import getopt
import traceback

from PIL import Image, UnidentifiedImageError


class ProgramError(Exception):
    pass


def convert_png(png_file):
    try:
        image = Image.open(png_file, formats = ['PNG'])
    except UnidentifiedImageError as error:
        raise ProgramError(f'Invalid PNG image: {png_file}')
    except (FileNotFoundError, PermissionError, IsADirectoryError) as error:
        raise ProgramError(f'{error.strerror}: {error.filename}')

    # Convert to grayscale then convert to palette based
    image = image.convert(mode = 'L').convert(mode = 'P', colors = 4)

    byte = 0
    slot = 0

    for y in range(0, image.height):
        for x in range(0, image.width):
            # Invert color
            pixel = 3 - (image.getpixel((x, y)) // 85)

            byte |= pixel << slot
            slot += 2

            if slot == 8 or (y == image.height - 1 and x == image.width - 1):
                print(f'{byte:02X}', end = '')

                byte = 0
                slot = 0

    print('')


def convert_cip(cip_data, width, height, png_file):
    pixels = []

    for byte in bytes.fromhex(cip_data):
        for _ in range(0, 4):
            # 0 is White, 1 is Light Gray, 2 is Dark Gray, 3 is Black
            pixels.append(255 - (85 * (byte & 3)))
            byte >>= 2

    if len(pixels) < width * height:
        raise ProgramError(f'Invalid CIP data length: {len(pixels)}')

    image = Image.new(mode = 'L', size = (width, height), color = 0)

    for y in range(0, height):
        for x in range(0, width):
            image.putpixel((x, y), pixels[(y * width) + x])

    try:
        image.save(png_file, 'PNG')
    except (PermissionError, IsADirectoryError) as error:
        raise ProgramError(f'{error.strerror}: {error.filename}')

    print(f'Saved {png_file}')


def main():
    try:
        short_options = 'd:w:h:H'
        long_options = ['data=', 'width=', 'height=', 'help']

        try:
            options, arguments = getopt.gnu_getopt(sys.argv[1:], short_options, long_options)
        except getopt.GetoptError as error:
            raise ProgramError(error.msg[0].upper() + error.msg[1:] +
                               '. Try \'' + os.path.basename(sys.argv[0]) + ' --help\' for more information')

        png_file = None
        cip_data = None
        width = None
        height = None
        help = False

        for option, argument in options:
            if option in ('-d', '--data'):
                cip_data = argument

            elif option in ('-w', '--width'):
                width = argument

                try:
                    width = int(width)

                    if width < 1:
                        raise ValueError

                except ValueError:
                    raise ProgramError(f'Invalid width: {width}')

            elif option in ('-h', '--height'):
                height = argument

                try:
                    height = int(height)

                    if height < 1:
                        raise ValueError

                except ValueError:
                    raise ProgramError(f'Invalid height: {height}')

            elif option in ('-H', '--help'):
                help = True

        if help:
            print('Usage: ' + os.path.basename(sys.argv[0]) + ' PNG-FILE\n'
                  'Convert a PNG into an grayscale 4-color CIP image.\n'
                  '\n'
                  '  -d, --data DATA        convert CIP image data to PNG\n'
                  '  -w, --width WIDTH      width of the CIP image\n'
                  '  -h, --height HEIGHT    height of the CIP image\n'
                  '  -H, --help             print this help and exit\n'
                  '\n')

            return

        if not len(arguments):
            raise ProgramError('No image specified')

        png_file = arguments[0]

        if not png_file.endswith('.png'):
            raise ProgramError(f'File name does not end with .png: {png_file}')

        if cip_data is not None:
            if width is None:
                raise ProgramError('No width specified')

            if height is None:
                raise ProgramError('No height specified')

            convert_cip(cip_data, width, height, png_file)
        else:
            convert_png(png_file)

    except ProgramError as error:
        print(str(error), file = sys.stderr)
        exit(1)

    except Exception:
        traceback.print_exc(file = sys.stderr)
        exit(1)

    exit(0)


if __name__ == '__main__':
    main()
