#!/usr/bin/env python3
#
# Copyright (c) 2020 Gareth Palmer <gareth.palmer3@gmail.com>
# This program is free software, distributed under the terms of
# the GNU General Public License Version 2.

import sys
import os.path
import re
import getopt
import traceback

import requests
import requests.auth
import requests.adapters
from lxml import etree


class ProgramError(Exception):
    pass


class HTTPSAdapter(requests.adapters.HTTPAdapter):
    def init_poolmanager(self, *args, **kwargs):
        kwargs['assert_hostname'] = False
        super().init_poolmanager(*args, **kwargs)


def get_info(hostname, port, timeout, info, username, password, certificate_file):
    if info in ('call', 'line', 'settings', 'mode'):
        # call -> CallInfo, line -> LineInfo, settings -> SettingsInfo, mode -> ModeInfo
        path = 'CGI/' + info[0].upper() + info[1:] + 'Info'
    elif info in ('device', 'ethernet'):
        # device -> DeviceInformationX, ethernet -> EthernetInformationX
        path = info[0].upper() + info[1:] + 'InformationX'
    elif info == 'network':
        # network -> NetworkConfigurationX
        path = 'NetworkConfigurationX'
    elif info in ('port1', 'port2'):
        # portN -> PortInformationX?N
        path = 'PortInformationX?' + info[-1]
    elif info == 'log':
        # log -> DeviceLogX?0
        path = 'DeviceLogX?0'
    elif info in ('streaming1', 'streaming2', 'streaming3'):
        # streamingN -> StreamingStatisticsX?N
        path = 'StreamingStatisticsX?' + info[-1]

    if username != '':
        authentication = requests.auth.HTTPBasicAuth(username, password)
    else:
        authentication = None

    scheme = 'https' if certificate_file else 'http'

    try:
        session = requests.Session()
        session.mount('https://', HTTPSAdapter())

        response = session.get(f'{scheme}://{hostname}:{port}/{path}',
                               timeout = timeout, auth = authentication, verify = certificate_file)

    except requests.RequestException as error:
        raise ProgramError(error)

    if response.status_code != 200:
        raise ProgramError(f'{response.status_code} {response.reason}')

    # 79xx sends text/html for ModeInfo
    if response.headers['Content-Type'][0:8] != 'text/xml' and response.headers['Content-Type'][0:9] != "text/html":
        raise ProgramError('Invalid content-type: ' + response.headers['Content-Type'])

    try:
        # 79xx sends multiple inline <?xml encoding="xxx"?> elements for DeviceLogX
        if info == 'log':
            document = etree.fromstring(re.sub(r'(?x) <\? xml .*? \?>', '', response.content.decode('utf-8')),
                                        etree.XMLParser(remove_blank_text = True))

            for element in document.findall('status'):
                # Move the timestamp text to an attribute so the output will format correctly
                element.set('time', element.text.strip())

                element.text = None
                element.find('./').tail = None

        else:
            document = etree.fromstring(response.content, etree.XMLParser(remove_blank_text = True))

    except etree.XMLSyntaxError as error:
        raise ProgramError(error)

    print(etree.tostring(document, pretty_print = True).decode('utf-8'), end = '')


def main():
    try:
        short_options = 'h:t:u:p:c:H'
        long_options = ['host=', 'timeout=', 'username=', 'password=', 'certificate=', 'help']

        try:
            options, arguments = getopt.gnu_getopt(sys.argv[1:], short_options, long_options)
        except getopt.GetoptError as error:
            raise ProgramError(error.msg[0].upper() + error.msg[1:] +
                               '. Try \'' + os.path.basename(sys.argv[0]) + ' --help\' for more information')

        hostname = None
        port = None
        timeout = 10
        username = ''
        password = ''
        certificate_file = None
        help = False

        for option, argument in options:
            if option in ('-h', '--host'):
                hostname = argument

                if ':' in hostname:
                    hostname, port = hostname.rsplit(':', maxsplit = 1)

                    try:
                        port = int(port)

                        if port < 1 or port > 65535:
                            raise ValueError

                    except ValueError:
                        raise ProgramError(f'Invalid port: {port}')

                if not re.search(r'(?xi) ^ (?: [a-z0-9\-]+ \.)* [a-z0-9\-]+ $', hostname):
                    raise ProgramError(f'Invalid host: {hostname}')

            elif option in ('-t', '--timeout'):
                timeout = argument

                try:
                    timeout = int(timeout)

                    if timeout < 1:
                        raise ValueError

                except ValueError:
                    raise ProgramError(f'Invalid timeout: {timeout}')

            elif option in ('-u', '--username'):
                username = argument

            elif option in ('-p', '--password'):
                password = argument

            elif option in ('-c', '--certificate'):
                certificate_file = argument

            elif option in ('-H', '--help'):
                help = True

        if help:
            print('Usage: ' + os.path.basename(sys.argv[0]) + ' [OPTIONS] INFO\n'
                  'Get status information as XML from a Cisco IP Phone.\n'
                  '\n'
                  '  -h, --host HOST[:PORT]         host name or IP address and port of the phone\n'
                  '  -t, --timeout TIMEOUT          connection timeout in seconds (default 10)\n'
                  '  -u, --username USERNAME        authentication username\n'
                  '  -p, --password PASSWORD        authentication password\n'
                  '  -c, --certificate CERT-FILE    connect using HTTPS and verify using certificate\n'
                  '  -H, --help                     print this help and exit\n'
                  '\n'
                  'INFO is one of either line, call, settings, mode, device, ethernet, network,\n'
                  'port1, port2, log, streaming1, streaming2 and streaming3.\n')

            return

        if not len(arguments):
            raise ProgramError('No mode specified')

        info = arguments[0]

        if info not in ('line', 'call', 'settings', 'mode', 'device', 'ethernet', 'network',
                        'port1', 'port2', 'log', 'streaming1', 'streaming2', 'streaming3'):
            raise ProgramError(f'Invalid info: {info}')

        if hostname is None:
            raise ProgramError('No host specified')

        if port is None:
            port = 443 if certificate_file else 80

        get_info(hostname, port, timeout, info, username, password, certificate_file)

    except ProgramError as error:
        print(str(error), file = sys.stderr)
        exit(1)

    except Exception:
        traceback.print_exc(file = sys.stderr)
        exit(1)

    exit(0)


if __name__ == '__main__':
    main()
